<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.jonavcar.ecommerce</groupId>
    <artifactId>ms-ecommerce</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <server.resource>sales</server.resource>
        <compiler-plugin.version>3.14.1</compiler-plugin.version>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>3.30.1</quarkus.platform.version>
        <openapi-generator.version>7.13.0</openapi-generator.version>
        <skipITs>true</skipITs>
        <surefire-plugin.version>3.5.4</surefire-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <repositories>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kafka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-config-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-redis-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-confluent-registry-avro</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.vault</groupId>
            <artifactId>quarkus-vault</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-avro</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>

        <!-- Dependencia Confluent para Avro -->
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-avro-serializer</artifactId>
            <version>7.7.0</version>
        </dependency>

        <!-- Bean Validation -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>

        <!-- CXF Dependency for JAX-RS Frontend (No recommend)-->
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxrs</artifactId>
            <version>4.1.1</version>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                            <goal>native-image-agent</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator.version}</version>
                <executions>
                    <!-- REST Server Code Generation -->
                    <execution>
                        <id>jonavcar-quarkus-core-openapi-generator-server</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/openapi/openapi.yaml</inputSpec>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <generatorName>jaxrs-spec</generatorName>
                            <configOptions>
                                <identifierNamingConvention>camelCase</identifierNamingConvention>
                                <apiPackage>${project.groupId}.resource.web</apiPackage>
                                <modelPackage>${project.groupId}.${server.resource}.model.api</modelPackage>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <sourceFolder>src/gen/java</sourceFolder>
                                <useSwaggerAnnotations>false</useSwaggerAnnotations>
                                <interfaceOnly>true</interfaceOnly>
                            </configOptions>
                        </configuration>
                    </execution>

                    <!-- REST Client Code Generation -->
                    <execution>
                        <id>jonavcar-quarkus-core-openapi-client-v1</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/openapi/client/openapi-client-v1.yaml</inputSpec>
                            <ignoreFileOverride>${project.basedir}/.openapi-generator-ignore</ignoreFileOverride>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generatorName>java</generatorName>
                            <!--<generateSupportingFiles>false</generateSupportingFiles>-->
                            <configOptions>
                                <apiPackage>${project.groupId}.${server.resource}.proxy</apiPackage>
                                <configPackage>${project.groupId}.${server.resource}.config</configPackage>
                                <modelPackage>
                                    ${project.groupId}.${server.resource}.model.proxy.client</modelPackage>
                                <serializationLibrary>jackson</serializationLibrary>
                                <useRuntimeException>true</useRuntimeException>
                                <microprofileRestClientVersion>3.0</microprofileRestClientVersion>
                                <useBeanValidation>true</useBeanValidation>
                                <useSealedInterfaces>true</useSealedInterfaces>
                                <identifierNamingConvention>camelCase</identifierNamingConvention>
                                <useSingleRequestParameter>false</useSingleRequestParameter>
                                <implicitHeaders>true</implicitHeaders>
                                <implicitHeadersRegex></implicitHeadersRegex>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                            </configOptions>
                            <library>microprofile</library>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jonavcar-quarkus-core-openapi-product-v1</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/openapi/client/openapi-product-v1.yaml</inputSpec>
                            <ignoreFileOverride>${project.basedir}/.openapi-generator-ignore</ignoreFileOverride>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generatorName>java</generatorName>
                            <!--<generateSupportingFiles>false</generateSupportingFiles>-->
                            <configOptions>
                                <apiPackage>${project.groupId}.${server.resource}.proxy</apiPackage>
                                <configPackage>${project.groupId}.${server.resource}.config</configPackage>
                                <modelPackage>
                                    ${project.groupId}.${server.resource}.model.proxy.product</modelPackage>
                                <serializationLibrary>jackson</serializationLibrary>
                                <useRuntimeException>true</useRuntimeException>
                                <microprofileRestClientVersion>3.0</microprofileRestClientVersion>
                                <useBeanValidation>true</useBeanValidation>
                                <useSealedInterfaces>true</useSealedInterfaces>
                                <identifierNamingConvention>camelCase</identifierNamingConvention>
                                <useSingleRequestParameter>false</useSingleRequestParameter>
                                <implicitHeaders>true</implicitHeaders>
                                <implicitHeadersRegex></implicitHeadersRegex>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                            </configOptions>
                            <library>microprofile</library>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <parameters>true</parameters>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>add-generated-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>
                                    ${project.build.directory}/generated-sources/openapi/src/gen/java</source>
                                <source>
                                    ${project.build.directory}/generated-sources/openapi/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!--
            <plugin>
                <groupId>com.google.code.maven-replacer-plugin</groupId>
                <artifactId>replacer</artifactId>
                <version>1.5.3</version>
                <executions>
                    <execution>
                        <id>fix-apiexception-imports</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <basedir>
                                ${project.build.directory}/generated-sources/openapi/src/main/java</basedir>
                            <includes>
                                <include>**/*Api.java</include>
                            </includes>
                            <replacements>
                                <replacement>
                                    <token>(package com\.jonavcar\.ecommerce\.sales\.proxy;)</token>
                                    <value>$1
import com.jonavcar.ecommerce.sales.exception.ApiException;
import com.jonavcar.ecommerce.sales.exception.ApiExceptionMapper;
                                    </value>
                                </replacement>
                                <replacement>
                                    <token>@RegisterProvider\(ApiExceptionMapper\.class\)</token>
                                    <value>
                                        @RegisterProvider(com.jonavcar.ecommerce.sales.exception.ApiExceptionMapper.class)
                                    </value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            -->

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <systemPropertyVariables>
                        <native.image.path>
                            ${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <properties>
                <skipITs>false</skipITs>
                <quarkus.native.enabled>true</quarkus.native.enabled>
            </properties>
        </profile>
    </profiles>
</project>