/**
 * Product Service API
 * External product service for querying product information
 * <p>
 * The version of the OpenAPI document: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.jonavcar.ecommerce.sales.exception;

import jakarta.ws.rs.core.Response;

public class ApiException extends RuntimeException {

    private static final long serialVersionUID = 1L;
    private Response response;

    public ApiException() {
        super();
    }

    public ApiException(Response response) {
        super("Api response has status code " + response.getStatus());
        this.response = response;
    }

    public Response getResponse() {
        return this.response;
    }
}
